---
- hosts: all
  remote_user: "{{ remote_user }}"
  become: yes
  roles:
    - common
    - role: certbot
      when: "'webserver' in group_names"
      tags: [ nginx, webserver ]
    - role: nginx
      when: "'webserver' in group_names"
      tags: [ nginx, webserver ]
    - role: php-fpm
      when: "'owncloud' in group_names"
      tags: [ php-fpm ]
    - role: postgresql
      when: "'database' in group_names"
      tags: [ postgresql ]
    - role: owncloud
      when: "'owncloud' in group_names"
      tags: [ owncloud ]
