---
- name: Check existing key
  stat: path=/etc/letsencrypt/live/{{ ansible_host }}/privkey.pem
  register: key_file

- name: Ask for a certificate from Lets Encrypt
  shell: "yes | /opt/letsencrypt/certbot-auto certonly --agree-tos --webroot -w {{ certbot_www_dir }} -d {{ ansible_host }} --email {{ certbot_admin_email }}"
  when: key_file.stat.islnk is not defined
